spring:
  application:
    name: mqtt

server:
  port: 9092

mqtt:
  # EMQX
  broker: tcp://broker.emqx.io:1883

  # Mosquitto
  # broker: tcp://localhost:1884
  # Mosquitto
  # broker: tcp://broker.emqx.io:1883
  client-id: spring-boot-client
  default-topic: sensor/data
  qos: 0
